# Generated by Django 3.0.2 on 2020-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationNo', models.IntegerField(primary_key=True, serialize=False)),
                ('applicationDate', models.DateField()),
                ('resolutionNo', models.CharField(max_length=50)),
                ('resolutionDate', models.DateField()),
                ('sarpanchRemark', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('houseNo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('establishmentName', models.CharField(max_length=150)),
                ('noOfRooms', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('vaddo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=100)),
                ('contactNo', models.IntegerField(default=9999999999)),
                ('vaddo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeTax', models.IntegerField(default=0)),
                ('boardTax', models.IntegerField(default=0)),
                ('garbageTax', models.IntegerField(default=0)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
