# Generated by Django 3.0.2 on 2020-07-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200730_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buisness',
            old_name='c',
            new_name='noOfRooms',
        ),
    ]
