# Generated by Django 3.0.2 on 2020-07-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20200730_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buisness',
            old_name='noOfRooms',
            new_name='Rooms',
        ),
    ]
