# Generated by Django 3.0.2 on 2020-07-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20200730_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buisness',
            old_name='Rooms',
            new_name='rooms',
        ),
    ]
